site_name: NUCLEAR Docs

nav:
    - Home: index.md
    - Setting up: installation.md
    - How it works: methods.md
    - Examples: examples.md 
    - Parameters: parameters.md
    - Citing: citing.md



markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  
theme:
  name: material
  custom_dir: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.expand
    - toc.integrate 

  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-6
        name: Switch to light mode
          
repo_url: https://github.com/rglez/nuclear/
repo_name: nuclear git repo



# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: docs/requirements.txt

mkdocs:
  configuration: docs/mkdocs.yml


